// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller.js"
application.register("autohide", AutohideController)

import CheckCurrentUserController from "./check_current_user_controller.js"
application.register("check-current-user", CheckCurrentUserController)
